#!/usr/bin/env python3
"""
corporate_documents_search.py

Client wrapper and compatibility layer for corporate documents search.
The core RAG engine logic is implemented in the self-contained app/mcp_server.py.
"""

from __future__ import annotations
import os
import sys
import asyncio
import logging
from typing import List, Dict, Any, Tuple, Optional

# Ensure the app directory is in sys.path
current_dir = os.path.dirname(os.path.abspath(__file__))
app_dir = os.path.dirname(current_dir)
if app_dir not in sys.path:
    sys.path.insert(0, app_dir)

# Setup logging
logger = logging.getLogger("DocumentSearchAgent")





async def _async_doc_rag_search_mcp(query: str, ticker: str, form_type: str) -> str:
    from mcp import ClientSession
    from mcp.client.sse import sse_client
    
    server_url = os.environ.get("DOCUMENT_SEARCH_MCP_URL", "http://127.0.0.1:8010/sse")
    logger.info(f"Connecting to document search MCP service via HTTP SSE at: {server_url}")
    
    async with sse_client(url=server_url, timeout=600.0) as (read, write):
        async with ClientSession(read, write) as session:
            await session.initialize()
            result = await session.call_tool(
                name="doc_rag_search",
                arguments={
                    "query": query,
                    "ticker": ticker,
                    "form_type": form_type
                }
            )
            ans = ""
            for content in result.content:
                if hasattr(content, "text"):
                    ans += content.text
                elif isinstance(content, dict) and "text" in content:
                    ans += content["text"]
            return ans


def doc_rag_search(query: str, ticker: str, form_type: str) -> str:
    """
    Executes a Retrieval-Augmented Generation (RAG) search over corporate filings and transcripts.
    This tool should be used to retrieve synthesized answers to research questions about specific 
    companies using official SEC filings and earnings call dialogue.
    
    Args:
        query (str): The search query, question, or research topic (e.g., 'Blackwell chip shipment timelines').
        ticker (str): The stock ticker symbol of the company (e.g., 'NVDA', 'AAPL', 'MSFT').
        form_type (str): The source filing category to target. Must be one of:
            - "10-K": Annual reports detailing long-term business overview, financial statements, and Item 1A Risk Factors. Supports retrieval across the last 5-10 years.
            - "10-Q": Quarterly reports containing recent balance sheets, operations remarks, and short-term trends. Supports retrieval across the last 8-12 quarters (2-3 years).
            - "8-K": Current reports filed to report immediate material events (e.g., acquisitions, earnings press releases). Supports retrieval across the last 1-2 years.
            - "Earnings" (or "EARNINGS_CALL"): Earnings call transcripts capturing dialogue between analysts and executives. Supports retrieval across the last 8-12 quarters (2-3 years).
            
    Returns:
        str: A synthesized, factual response generated by the multi-agent supervisor system.
    """
    try:
        loop = asyncio.get_event_loop()
    except RuntimeError:
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
        
    if loop.is_running():
        import threading
        res_list = []
        def run_in_thread():
            new_loop = asyncio.new_event_loop()
            asyncio.set_event_loop(new_loop)
            res = new_loop.run_until_complete(_async_doc_rag_search_mcp(query, ticker, form_type))
            res_list.append(res)
            new_loop.close()
        t = threading.Thread(target=run_in_thread)
        t.start()
        t.join()
        return res_list[0] if res_list else ""
    else:
        return loop.run_until_complete(_async_doc_rag_search_mcp(query, ticker, form_type))



